### model
model_name_or_path: /scratch/esg8sdce/pre_trained_models/Qwen2.5-VL-7B-Instruct_cotkl_scienceqa
image_max_pixels: 4194304
trust_remote_code: true

flash_attn: fa2


### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false  # choices: [true, false]
freeze_multi_modal_projector: false  # choices: [true, false]
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset #7168
dataset: textvqa_train, cotkl_textvqa_train
template: qwen2_vl
cutoff_len: 8192
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /scratch/esg8sdce/pre_trained_models/Qwen2.5-VL-7B-Instruct_cotkl_scienceqa_textvqa
logging_steps: 10
save_steps: 100000
save_strategy: "no"
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

## eval
eval_dataset: textvqa_test
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 100000
compute_accuracy_vqa: true
eval_on_start: true


# llamafactory-cli train examples/train_full/mllm_cl/qwen2_5vl_scienceqa_textvqa.yaml
# nohup llamafactory-cli train examples/train_full/mllm_cl/qwen2_5vl_scienceqa_textvqa.yaml > /home/esg8sdce/esg8sdceuser01/project/LLaMA-Factory/examples/train_full/cotkl_2_textvqa.log 2>&1 &